### PR TITLE
Update API docs in readme.md

### PR DESCRIPTION
**Pull request by juanmanual**
Updates API docs to use objects instead of named parameters.

### CODE REVIEW

**Comment by filmaj** [comment]
Hey thanks so much for the PR! If you could sign the CLA by clicking here: https://cla.js.foundation/architect/hydrate?pullRequest=17 and signing in with github, that'd be the last thing we need to accept your contribution!

**Comment by juanmanual** [comment]
I did sign the CLA but for some reason it's still showing as pending. Does it take time to process?

**Comment by filmaj** [comment]
I'm not sure... @ryanblock @brianleroux any ideas what with this JSF bot?

**Comment by ryanblock** [comment]
There shouldn't be any lag, @juanmanual can you try again?

I have seen occasional issues with the CLA assistant though, I wonder if OJS (neé JSF) is due for an upgrade to the CLA assistant app.

**Comment by brianleroux** [comment]
ping @juanmanual ! 🙏

**Comment by ryanblock** [comment]
Fixed in https://github.com/architect/hydrate/blob/main/readme.md

**Pull request closed without merging**
